### ISSUE TITLE
Within a mutation lineage graph, when supressing all mutations except for the one of interest, the y-axis scale becomes unreadable.

### ISSUE THREAD

**Issue by pvphaneuf** [dmccloskey/ddt#1]

**Comment by pvphaneuf** [comment]
![working](https://cloud.githubusercontent.com/assets/4079329/9156404/dc5b4b92-3e8d-11e5-9c5c-a3d5e653f6e6.png)
![not_working](https://cloud.githubusercontent.com/assets/4079329/9156405/e40f815a-3e8d-11e5-81fe-1cc24e8db75c.png)

With the "not_working.png" screenshot, you can't tell what the frequency is on a mutation that is has 100% frequency for all samples.

**Comment by dmccloskey** [comment]
Problem:  This is caused by an auto-adjustment of the y-axis from min_value(data array) to max_value(data array).  When only one or a constant y-value is supplied, the min/max of the y-axis are set to the same value.  
Correction (TODO): ensure a minimum y-axis value of 0.

**Comment by dmccloskey** [comment]
Fixed
![figure](https://cloud.githubusercontent.com/assets/5378614/9156946/6a72fdb0-3e9f-11e5-8e47-37d2a1a5991e.png)
